### ISSUE TITLE
/usr/include/obs/obs-internal.h references caption/caption.h but make install does not install that header

### ISSUE THREAD

**Issue by darix** [obsproject/obs-studio#3925]
obs-studio 26.1.0

as the subject line says the headers are missing in the make install target or should not be pulled by the obs-internal header.

We found this by trying to build the obs gphoto2 plugin for openSUSE.

**Comment by WizardCM** [comment]
Please fill in the issue template.

**Comment by darix** [comment]
What informations are you missing?

**Comment by darix** [comment]
What would be the preferred path of action here: remove the reference to caption/caption.h in obs-internal.h or add a rule to cmake to install the headers from deps/libcaption/caption/ ?

**Comment by darix** [comment]
seems it was broken in https://github.com/obsproject/obs-studio/pull/2857

**Comment by maxdrash** [comment]
Same problem here, make stops:
```
 In file included from /obs-studio/libobs/obs-scene.h:21,
/obs-studio/libobs/obs-internal.h:39:10: fatal error: caption/caption.h: Aucun fichier ou dossier de ce type
 #include <caption/caption.h>
          ^~~~~~~~~~~~~~~~~~~
```

**Comment by darix** [comment]
For the opensuse rpm I prepared this workaround for now:

```
install -D -m 0755 -d                        %{buildroot}%{_includedir}/obs/caption/
install -D -m 0644 deps/libcaption/caption/* %{buildroot}%{_includedir}/obs/caption/
```
