### PR TITLE
 librtmp: Add mbedtls 3 compatibility

### LINKED ISSUE #5044: obs-studio-27.0.1 does not compile with mbedtls-3.0.0
### Operating System Info

Other

### Other OS

Gentoo Linux

### OBS Studio Version

27.0.1

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

N/A

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Flawless compilation :)

### Current Behavior

[144/375] /usr/bin/x86_64-pc-linux-gnu-gcc -DCRYPTO -DHAVE_OBSCONFIG_H -DUSE_MBEDTLS -DUSE_XDG -Dobs_outputs_EXPORTS -I/var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1_build/plugins/obs-outputs/config -I/var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1/libobs -I/var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1_build/config  -Wall -Wextra -Wvla -Wno-unused-function -Werror-implicit-function-declaration -Wno-missing-braces -Wno-missing-field-initializers -O2 -march=znver3 -pipe -g -ggdb -std=gnu99 -fno-strict-aliasing -fPIC -mmmx -msse -msse2 -pthread -fvisibility=hidden -MD -MT plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o -MF plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o.d -o plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o -c /var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1/plugins/obs-outputs/librtmp/rtmp.c
FAILED: plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o 
/usr/bin/x86_64-pc-linux-gnu-gcc -DCRYPTO -DHAVE_OBSCONFIG_H -DUSE_MBEDTLS -DUSE_XDG -Dobs_outputs_EXPORTS -I/var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1_build/plugins/obs-outputs/config -I/var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1/libobs -I/var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1_build/config  -Wall -Wextra -Wvla -Wno-unused-function -Werror-implicit-function-declaration -Wno-missing-braces -Wno-missing-field-initializers -O2 -march=znver3 -pipe -g -ggdb -std=gnu99 -fno-strict-aliasing -fPIC -mmmx -msse -msse2 -pthread -fvisibility=hidden -MD -MT plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o -MF plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o.d -o plugins/obs-outputs/CMakeFiles/obs-outputs.dir/librtmp/rtmp.c.o -c /var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1/plugins/obs-outputs/librtmp/rtmp.c
In file included from /var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1/plugins/obs-outputs/librtmp/rtmp.c:178:
/var/tmp/portage/media-video/obs-studio-27.0.1/work/obs-studio-27.0.1/plugins/obs-outputs/librtmp/handshake.h:29:10: fatal error: mbedtls/arc4.h: No such file or directory
   29 | #include <mbedtls/arc4.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

### Steps to Reproduce

* Install mbedtls-3
* Attempt to compile obs-studio from source

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Mbed TLS 3 gave some changes like :
- RC4 removal needed by encrypted RTMP
- `fd` from mbedtls_net_context was temporarily put private
  - Since https://github.com/ARMmbed/mbedtls/pull/4842 is now merged, we know that `fd` will be only private on 3.0.0, on newer `fd` is public
  - On 3.0.0, since those access change were made, they temporarily allowed accessing them an other way
- Some MD5 methods that got their name change back

So to make OBS compatible with Mbed TLS 3, like R1CH mentions it [here](https://github.com/obsproject/obs-studio/issues/5044#issuecomment-888687493) we need to disable encrypted RTMP, ~~so this PR disables it if Mbed TLS 3 or newer is used to build OBS~~, a request to remove encrypted RTMP support was made in the comment.

### Motivation and Context

Fix #5044

### How Has This Been Tested?

- Build with mbedtls 2.27 and build with mbedtls 3.0.0
- Someone tested a RTMPS stream with a flatpak build with mbedtls 3 on my [proto PR](https://github.com/tytan652/obs-studio/pull/1)
- No test with encrypted RTMP were made, sorry

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested with RTMPS protocol.
- [ ] The code has been tested with encrypted RTMP protocol new behavior.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: plugins/obs-outputs/librtmp/rtmp.c [hunk 1]
```diff
@@ -1561,16 +1557,6 @@ WriteN(RTMP *r, const char *buffer, int n)
 #ifdef CRYPTO
     char *encrypted = 0;
     char buf[RTMP_BUFFER_CACHE_SIZE];
```
Comment (notr1ch) [inline plugins/obs-outputs/librtmp/rtmp.c:1559]: It looks like these variables (and the whole `#ifdef CRYPTO`) can also be removed, along with the code at the end of the function.

https://github.com/tytan652/obs-studio/blob/447366d9e134537cf3c37ba8cab56298ef436abe/plugins/obs-outputs/librtmp/rtmp.c#L1597-L1600

Comment (tytan652) [reply plugins/obs-outputs/librtmp/rtmp.c]: Changes pushed

**Review by notr1ch — APPROVED** [review]
