### PR TITLE
Separation of the controls dock from the main window

### PR DESCRIPTION
**Pull request by tytan652**
### Description

**Depends on:**
- #7169

Moves the controls dock UI outside of the main window UI.
And make OBSBasic no longer rely on UI element from the controls dock.

Also adds replay buffer buttons and the pause button in the UI file, those are no longer manually and programmatically created and deleted.

### Motivation and Context

This PR has two purpose:
- RFC 47, Switch to Advanced Docking System
- Allow replacement of this dock to be easier to implement like #6421 by relying on new signals and slots.

### How Has This Been Tested?

I tried to test all the feature of the dock, but please test it yourself too.

Need also some testing about what 2d60c89a02e5f1559603ed83de08a05e2077101a was fixing because we no longer rely on UI elements.

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

- Code cleanup (non-breaking change which makes code smaller or more readable)

- Refactor for future features

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
Remove from the milestone, because it is related to the RFC about MVC.

File: UI/window-basic-main.cpp [hunk 1]
```diff
@@ -6931,9 +6996,6 @@ void OBSBasic::YoutubeStreamCheck(const std::string &key)
 		auto item = json["items"][0];
 		auto status = item["status"]["streamStatus"].string_value();
 		if (status == "active") {
-			QMetaObject::invokeMethod(ui->broadcastButton,
-						  "setEnabled",
-						  Q_ARG(bool, true));
```
Comment (tytan652) [inline UI/window-basic-main.cpp:6936]: TODO: Found a situation when `ui->broadcastButton` is disabled while running the check.

**Comment by tytan652** [comment]
The PR has been entirely refactored, it still miss appearance/theming bits for the small buttons of the dock.

**Comment by tytan652** [comment]
#9653 was merged, so I finished theming the small button.

File: UI/window-basic-main.cpp (hunk 1 above)
Comment (tytan652) [reply UI/window-basic-main.cpp:6927]: Done

File: UI/basic-controls.cpp [hunk 2]
```diff
@@ -0,0 +1,321 @@
...
+	connect(
+		stopStreamAction.data(), &QAction::triggered, this,
+		[this]() { emit this->StopStreamMenuActionClicked(); },
+		Qt::DirectConnection);
+	connect(
+		forceStopStreamAction, &QAction::triggered, this,
+		[this]() { emit this->ForceStopStreamMenuActionClicked(); },
+		Qt::DirectConnection);
+
+	/* Setup default visibilty */
```
Comment (RytoEX) [inline UI/basic-controls.cpp:80]:
```suggestion
	/* Set up default visibility */
```

File: UI/basic-controls.cpp [hunk 3]
```diff
@@ -0,0 +1,321 @@
...
+	ui->broadcastButton->setVisible(false);
+	ui->pauseRecordButton->setVisible(false);
+	ui->replayBufferButton->setVisible(false);
+	ui->saveReplayButton->setVisible(false);
+	ui->virtualCamButton->setVisible(false);
+	ui->virtualCamConfigButton->setVisible(false);
+
+	/* Setup state update connections */
```
Comment (RytoEX) [inline UI/basic-controls.cpp:88]:
```suggestion
	/* Set up state update connections */
```

File: UI/basic-controls.cpp [hunk 4]
```diff
@@ -0,0 +1,321 @@
...
+
+	connect(main, &OBSBasic::VirtualCamStarted, this,
+		&OBSBasicControls::VirtualCamStarted);
+	connect(main, &OBSBasic::VirtualCamStopped, this,
+		&OBSBasicControls::VirtualCamStopped);
+
+	connect(main, &OBSBasic::PreviewProgramModeChanged, this,
+		&OBSBasicControls::UpdateStudioModeState);
+
+	/* Setup enablement connection */
```
Comment (RytoEX) [inline UI/basic-controls.cpp:131]:
```suggestion
	/* Set up enablement connection */
```

File: UI/window-basic-main.hpp [hunk 5]
```diff
@@ -1247,9 +1255,45 @@ public slots:
...
+	void StreamingStopping();
+	void StreamingStopped(bool withDelay = false);
+
+	/* Broadcast Flow signals */
+	void BroadcastFlowEnabled(bool enabled);
+	void BroadcastStreamReady(bool ready);
+	void BroadcastStreamActive();
+	void BroadcastStreamStarted(bool autoStop);
+
+	/* Recordings signals */
```
Comment (RytoEX) [inline UI/window-basic-main.hpp:1271]:
```suggestion
	/* Recording signals */
```

File: UI/window-basic-main.hpp [hunk 6]
```diff
@@ -1247,9 +1255,45 @@ public slots:
...
+	void RecordingStarted(bool pausable = false);
+	void RecordingPaused();
+	void RecordingUnpaused();
+	void RecordingStopping();
+	void RecordingStopped();
+
+	/* Replay buffer signals */
```
Comment (RytoEX) [inline UI/window-basic-main.hpp:1278]:
```suggestion
	/* Replay Buffer signals */
```

File: UI/window-basic-main.hpp [hunk 7]
```diff
@@ -1247,9 +1255,45 @@ public slots:
...
+	void ReplayBufEnabled(bool enabled);
+	void ReplayBufStarted();
+	void ReplayBufStopping();
+	void ReplayBufStopped();
+
+	/* Virtual camera signals */
```
Comment (RytoEX) [inline UI/window-basic-main.hpp:1284]:
```suggestion
	/* Virtual Camera signals */
```

File: UI/window-basic-main.hpp [hunk 8]
```diff
@@ -1234,6 +1222,26 @@ private slots:
...
+
+	/* Replay Buffer action (start/stop) slot */
+	void ReplayBufferActionTriggered();
+
+	/* Virtual Cam action (start/stop) slots */
+	void VirtualCamActionTrigerred();
+
+	void OpenVirtualCamConfig();
+
+	/* Studio mode toggle slot */
```
Comment (RytoEX) [inline UI/window-basic-main.hpp:1242]:
```suggestion
	/* Studio Mode toggle slot */
```

File: UI/window-basic-main.hpp [hunk 9]
```diff
@@ -1247,9 +1255,45 @@ public slots:
...
+	void ReplayBufStarted();
+	void ReplayBufStopping();
+	void ReplayBufStopped();
+
+	/* Virtual camera signals */
+	void VirtualCamEnabled();
+	void VirtualCamStarted();
+	void VirtualCamStopped();
+
+	/* Studio mode signal */
```
Comment (RytoEX) [inline UI/window-basic-main.hpp:1289]:
```suggestion
	/* Studio Mode signal */
```

**Review by RytoEX — CHANGES_REQUESTED** [review]
Nits, mostly.

> UI: Do not user controls dock as a source for text 

user -> use

Though, I wonder if these commit messages could be more clear/expressive if they described what they _were_ doing rather than what they were _not_ doing.

**Comment by RytoEX** [comment]
Apparently I forgot to submit a comment.

About UI/noncheckable-buttons.hpp, I am a little confused by its purpose. QPushButtons have checkable set to false by default. Are we sub-classing it just to communicate "you shouldn't set checkable to true on this", but not actually preventing it from being done?

**Comment by tytan652** [comment]
> About UI/noncheckable-buttons.hpp, I am a little confused by its purpose. QPushButtons have checkable set to false by default. Are we sub-classing it just to communicate "you shouldn't set checkable to true on this", but not actually preventing it from being done?

The name I chose was not best I know.

In styling we rely on the `checked` state, but this state is kept to `false` if `checkable` is set to `false`, so we need the button to stay with `checkable` to `true`.

The main issue that `NonCheckableButton` try to solve, is that we have a scenario (multiple times) with multiple outcomes where all of them except mostly one ends up with only `setChecked(false)` (so undoing the automatic change done by clicking the button).
So to simplify the code, I reversed that logic and overridden `nextCheckState()` to not change `checked` each time we click on the button, to change manually `checked` when it really needs to be change which happens in really fewer outcomes.

**Comment by tytan652** [comment]
> Nits, mostly.

I fixed them.

> Though, I wonder if these commit messages could be more clear/expressive if they described what they _were_ doing rather than what they were _not_ doing.

I'll try to find better names.

File: UI/basic-controls.cpp [hunk 10]
```diff
@@ -0,0 +1,321 @@
...
+}
+
+void OBSBasicControls::StreamingStarted(bool withDelay)
+{
+	ui->streamButton->setEnabled(true);
+	ui->streamButton->setChecked(true);
+	ui->streamButton->setText(QTStr("Basic.Main.StopStreaming"));
+
+	if (withDelay) {
+		ui->streamButton->setMenu(streamButtonMenu.data());
```
Comment (RytoEX) [inline UI/basic-controls.cpp:165]: Consider `.get()`, which is an alias of `.data()` and aligns with std::unique_ptr.
```suggestion
		ui->streamButton->setMenu(streamButtonMenu.get());
```

File: UI/basic-controls.cpp [hunk 11]
```diff
@@ -0,0 +1,321 @@
...
+
+void OBSBasicControls::StreamingStopped(bool withDelay)
+{
+	ui->streamButton->setEnabled(true);
+	ui->streamButton->setChecked(false);
+	ui->streamButton->setText(QTStr("Basic.Main.StartStreaming"));
+
+	if (withDelay) {
+		if (!ui->streamButton->menu())
+			ui->streamButton->setMenu(streamButtonMenu.data());
```
Comment (RytoEX) [inline UI/basic-controls.cpp:184]: Consider `.get()`, which is an alias of `.data()` and aligns with std::unique_ptr.
```suggestion
			ui->streamButton->setMenu(streamButtonMenu.get());
```

File: UI/window-basic-main.cpp [hunk 12]
```diff
@@ -8101,7 +8065,7 @@ void OBSBasic::OnVirtualCamStop(int)
 	QTimer::singleShot(100, this, &OBSBasic::RestartingVirtualCam);
 }
 
-void OBSBasic::on_streamButton_clicked()
+void OBSBasic::StreamActionTrigerred()
```
Comment (RytoEX) [inline UI/window-basic-main.cpp:8068]:
```suggestion
void OBSBasic::StreamActionTriggered()
```

File: UI/window-basic-main.cpp [hunk 13]
```diff
@@ -8197,17 +8151,15 @@ void OBSBasic::on_streamButton_clicked()
...
 				return;
-			}
 		}
 
 		StartStreaming();
 	}
 }
 
-void OBSBasic::on_recordButton_clicked()
+void OBSBasic::RecordActionTrigerred()
```
Comment (RytoEX) [inline UI/window-basic-main.cpp:8162]:
```suggestion
void OBSBasic::RecordActionTriggered()
```

File: UI/window-basic-main.cpp [hunk 14]
```diff
@@ -8221,37 +8173,31 @@ void OBSBasic::on_recordButton_clicked()
...
+		if (!UIValidation::NoSourcesConfirmation(this))
 			return;
-		}
 
 		StartRecording();
 	}
 }
 
-void OBSBasic::VCamButtonClicked()
+void OBSBasic::VirtualCamActionTrigerred()
```
Comment (RytoEX) [inline UI/window-basic-main.cpp:8188]:
```suggestion
void OBSBasic::VirtualCamActionTriggered()
```

**Review by RytoEX — CHANGES_REQUESTED** [review]

**Comment by tytan652** [comment]
@RytoEX, done

File: UI/basic-controls.cpp (hunk 10 above)
Comment (tytan652) [reply UI/basic-controls.cpp]: I also changed those that were in `OBSBasicControls` constructor.

**Comment by tytan652** [comment]
Renamed `noncheckable-buttons.hpp` to `noncheckable-button.hpp`.

File: UI/basic-controls.cpp [hunk 15]
```diff
@@ -0,0 +1,321 @@
...
+	ui->streamButton->setText(QTStr("Basic.Main.StartStreaming"));
+
+	if (withDelay) {
+		if (!ui->streamButton->menu())
+			ui->streamButton->setMenu(streamButtonMenu.get());
+
+		startStreamAction->setVisible(true);
+		stopStreamAction->setVisible(false);
+	} else
+		ui->streamButton->setMenu(nullptr);
```
Comment (RytoEX) [inline UI/basic-controls.cpp:189]:
```suggestion
	} else {
		ui->streamButton->setMenu(nullptr);
	}
```
When one branch of an if-else has brackets, all branches must have brackets.

File: UI/window-basic-main.hpp [hunk 16]
```diff
@@ -1247,9 +1255,45 @@ public slots:
...
+	void RecordingPaused();
+	void RecordingUnpaused();
+	void RecordingStopping();
+	void RecordingStopped();
+
+	/* Replay Buffer signals */
+	void ReplayBufEnabled(bool enabled);
+	void ReplayBufStarted();
+	void ReplayBufStopping();
+	void ReplayBufStopped();
```
Comment (RytoEX) [inline UI/window-basic-main.hpp:1282]:
```suggestion
	void ReplayBufferEnabled(bool enabled);
	void ReplayBufferStarted();
	void ReplayBufferStopping();
	void ReplayBufferStopped();
```
We can just use the full name like in `UI/basic-controls.hpp`.

**Review by RytoEX — CHANGES_REQUESTED** [review]
I'll give this a test later.

File: UI/window-basic-main.hpp (hunk 16 above)
Comment (tytan652) [reply UI/window-basic-main.hpp:1282]: We can't `ReplayBufferStopping` is a function in `OBSBasic`, so `ReplayBuf` was used for signals to avoid confusion with the existing function.

File: UI/basic-controls.cpp (hunk 15 above)
Comment (tytan652) [reply UI/basic-controls.cpp]: Brackets added.

File: UI/window-basic-main.hpp (hunk 16 above)
Comment (RytoEX) [reply UI/window-basic-main.hpp:1282]: Unfortunate.

**Review by Warchamp7 — APPROVED** [review]

**Comment by RytoEX** [comment]
After rebasing, this failed to build due to previous changes in `UI/window-basic-main.cpp` to `void OBSBasic::StartStreaming()`:
```cpp
	auto setStreamText = [&](const QString &text) {
		ui->streamButton->setText(text);
		if (sysTrayStream)
			sysTrayStream->setText(text);
	};
```
The compiler error was:
> no member named 'streamButton' in 'Ui::OBSBasic'

This is obvious in hindsight because this PR moves `streamButton` from OBSBasic to OBSBasicControls. To get this to compile, I removed this line:
https://github.com/obsproject/obs-studio/blob/0cc357f6dc3667593d182017a8074cc6ab044ee3/UI/window-basic-main.cpp#L7044

This does mean that the "Preparing..." text will no longer be shown on the "Start Stream" button. I'm not sure what to do about that.

**Comment by tytan652** [comment]
I added a commit that removes the lamdba, moreover `StreamingStarting` behavior got split in two by #10633 with a new `setText` which required moving a signal call and add a new one.

**Comment by RytoEX** [comment]
> I added a commit that removes the lamdba, moreover `StreamingStarting` behavior got split in two by #10633 with a new `setText` which required moving a signal call and add a new one.

Thanks for that. Will re-review shortly.

**Review by RytoEX — APPROVED** [review]
Gave a quick review and local build/run test after the recent force push. Seems fine.
