### PR TITLE
frontend: Fix build with Qt 6.12

### PR DESCRIPTION
**Pull request by Chiitoo**
### Description

This fixes compiling OBS Studio against Qt 6.12 (unreleased at the time of writing) .

### Motivation and Context

After Qt upstream commit 556028d16a0 [1], 'QHash' and 'QSet' need to be explicitly included when using 'QT_ENABLE_STRICT_MODE_UP_TO'.

Without these changes, compiling fails like so:

```
frontend/OBSApp.hpp:117:34: error: field ‘themes’ has incomplete type ‘QHash<QString, OBSTheme>’
  117 |         QHash<QString, OBSTheme> themes;
      |                                  ^~~~~~
```

```
frontend/OBSApp_Themes.cpp:440:23: error: aggregate ‘QSet<QString> invalid’ has incomplete type and cannot be defined
  440 |         QSet<QString> invalid;
      |                       ^~~~~~~
```

1. https://code.qt.io/cgit/qt/qtbase.git/commit/?id=556028d16a059006cc5a03676260aff5428b767e

### How Has This Been Tested?

Tested by compiling and running on Gentoo Linux, on amd64 (OBS Studio `git master` / Qt `6.12 git master`) and arm64 (OBS Studio `32.1.0` / Qt `6.10.3`) architectures.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.md).
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] My code follows the project's [**style guidelines**](https://github.com/obsproject/obs-studio/blob/master/CODESTYLE.md)
- [x] My code is not on the master branch.
- [x] My code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Chiitoo** [comment]
Per

https://github.com/obsproject/obs-studio/commit/e04b883e4bc8209e0719f0a8046c0360d7a8f513#diff-df7c79c06946f702a0332b4417268ced5a7f76c5dc4551fdad4df8f82cf4a450R4-R240

I'm unsure if these should now be in the form of `<QtCore/QHash>`... but so far I see exactly one such example, from 2019 or so.

**Comment by PatTheMav** [comment]
Please complete the PR checklist to ensure that the PR is eligible for review.

**Comment by Chiitoo** [comment]
> Please complete the PR checklist to ensure that the PR is eligible for review.

Done.

Apologies for the delay on those bits.

**Review by RytoEX — APPROVED** [review]
Even if Qt 6.12 is not yet released, QHash and QSet are used in these files respectively, so it makes sense to me to explicitly include them. @PatTheMav ?

**Review by PatTheMav — APPROVED** [review]
Yep and including them like this is fine (there's no need to use framework-specific includes).
