### ISSUE TITLE
OBS 31.0.0 beta1/2: compilation error:  call to '_curl_easy_setopt_err_write_callback'

### ISSUE THREAD

**Issue by AngryPenguinPL** [obsproject/obs-studio#11441]
### Operating System Info

Other

### Other OS

OpenMandriva

### OBS Studio Version

31.0.0-beta1

### OBS Studio Log URL

compilation error not runtime, so no OBS log

### Expected Behavior

All compile fine

### Current Behavior

When compiling OBS-Studio 31.0.0 beta 1 and 2 and applying this patch https://github.com/obsproject/obs-studio/pull/11437, which fixes previous compilation issues with bug https://github.com/obsproject/obs-studio/issues/11436
an another error occurs:
```
/builddir/build/BUILD/obs-studio-31.0.0-build/obs-studio-31.0.0-beta2/shared/file-updater/file-updater/file-updater.c:111:2: error: call to '_curl_easy_setopt_err_write_callback' declared with 'warning' attribute: curl_easy_setopt expects a curl_write_callback argument for this option [-Werror,-Wattribute-warning]
DEBUG util.py:463:    111 |         curl_easy_setopt(info->curl, CURLOPT_WRITEFUNCTION, http_write);
DEBUG util.py:463:        |         ^
DEBUG util.py:463:  /usr/include/curl/typecheck-gcc.h:59:15: note: expanded from macro 'curl_easy_setopt'
DEBUG util.py:463:     59 |               _curl_easy_setopt_err_write_callback();                   \
DEBUG util.py:463:        |               ^
DEBUG util.py:463:  /builddir/build/BUILD/obs-studio-31.0.0-build/obs-studio-31.0.0-beta2/shared/file-updater/file-updater/file-updater.c:120:3: error: call to '_curl_easy_setopt_err_write_callback' declared with 'warning' attribute: curl_easy_setopt expects a curl_write_callback argument for this option [-Werror,-Wattribute-warning]
DEBUG util.py:463:    120 |                 curl_easy_setopt(info->curl, CURLOPT_HEADERFUNCTION, http_header);
DEBUG util.py:463:        |                 ^
DEBUG util.py:463:  /usr/include/curl/typecheck-gcc.h:59:15: note: expanded from macro 'curl_easy_setopt'
DEBUG util.py:463:     59 |               _curl_easy_setopt_err_write_callback();                   \
DEBUG util.py:463:        |               ^
DEBUG util.py:463:  2 errors generated.
```

Full build log: https://file-store.openmandriva.org/api/v1/file_stores/a8b1035c65e7d5659ed08ef6ebff78667bb30a9c.log?show=true

Details:
Obs-Sudio 31.0.0 beta1/2
OpenMandriva Cooker
LLVM/Clang 19.1.2
cURL: 8.10.1

Worth to add it compile fine with gcc-14.2.0.

### Steps to Reproduce

1. Try compile obs 31.0.0 beta 1 or 2 on  Linux with Clang 19.1.2 after applying this patch: https://github.com/obsproject/obs-studio/pull/11437
2. See build error
...

**Comment by gxalpha** [comment]
If you have concerns about a specific Pull Request that is not yet merged, please voice them on the Pull Request directly.
Additionally, OpenMandriva is not officially supported. If you run into problems, please provide patches fixing them instead of opening issues.
