### ISSUE TITLE
macOS: After update to 26.1.0 always crashing on start

### ISSUE THREAD

**Issue by saspol** [obsproject/obs-studio#3939]
Previous version 26.0.2 working very well.
My system is High Sierra(10.13.6)
If you build it for macOS 10.15 and higher, this should be said with BIG LETTERS in Changelog.

```
Dec 19 16:10:27 Mitrys-iMac obs[4469]: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:10:27 Mitrys-iMac obs[4469]: dyld: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:10:38 Mitrys-iMac obs[4474]: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:10:38 Mitrys-iMac obs[4474]: dyld: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:10:48 Mitrys-iMac obs[4482]: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:10:48 Mitrys-iMac obs[4482]: dyld: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:10:58 Mitrys-iMac obs[4486]: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:10:58 Mitrys-iMac obs[4486]: dyld: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:11:25 Mitrys-iMac obs[4499]: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:11:25 Mitrys-iMac obs[4499]: dyld: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:13:03 Mitrys-iMac obs[549]: dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
Dec 19 16:13:03 Mitrys-iMac obs[549]: dyld: Symbol not found: ____chkstk_darwin
	  Referenced from: /Applications/OBS.app/Contents/MacOS/../Frameworks/libssl.1.1.dylib (which was built for Mac OS X 10.15)
```

**Comment by WizardCM** [comment]
Duplicate of #3887
