### ISSUE TITLE
fails to build with mbedtls 4.1.0

### ISSUE THREAD

**Issue by tippfehlr** [obsproject/obs-studio#13601]
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

32.1.2

### OBS Studio Log URL

this is a build-time issue, log below

### Expected Behavior

build successfully

### Current Behavior

the build fails with

```
/build/obs-studio/src/obs-studio/plugins/obs-outputs/librtmp/rtmp.h:63:10: fatal error: mbedtls/ctr_drbg.h: No such file or directory
   63 | #include <mbedtls/ctr_drbg.h>
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

[obs-mbedtls4-build.log](https://github.com/user-attachments/files/29399182/obs-mbedtls4-build.log)

### Steps to Reproduce

build obs-studio with mbedtls version 4.1.0.

**Comment by tytan652** [comment]
You'll have to stick with MbedTLS < 4 for now.

**Comment by tippfehlr** [comment]
Ok, thanks for your quick answer. Then see this as a tracking issue :)
